# Generated by Django 6.1.1 on 2026-09-18 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('plazo_limite', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('plazo', models.DateField()),
                ('horas_estimadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='core.evento')),
            ],
        ),
    ]
